"""baseline schema (phases 1-5)

Revision ID: 52f4c7b68fb8
Revises:
Create Date: 2026-09-25 00:25:58.260885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f4c7b68fb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('sif_potential', sa.String(length=3), nullable=False),
    sa.Column('site', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('activity', sa.String(length=100), nullable=False),
    sa.Column('barrier_failure', sa.String(length=100), nullable=True),
    sa.Column('pii_detected', sa.Integer(), nullable=False),
    sa.Column('pii_count', sa.Integer(), nullable=False),
    sa.Column('pii_types', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('ix_reports_activity', 'reports', ['activity'], unique=False)
    op.create_index('ix_reports_area', 'reports', ['area'], unique=False)
    op.create_index('ix_reports_barrier', 'reports', ['barrier_failure'], unique=False)
    op.create_index('ix_reports_category', 'reports', ['category'], unique=False)
    op.create_index('ix_reports_content_hash', 'reports', ['content_hash'], unique=True)
    op.create_index(op.f('ix_reports_date'), 'reports', ['date'], unique=False)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=False)
    op.create_index('ix_reports_risk_level', 'reports', ['risk_level'], unique=False)
    op.create_index('ix_reports_sif_potential', 'reports', ['sif_potential'], unique=False)
    op.create_index('ix_reports_site', 'reports', ['site'], unique=False)
    op.create_index('ix_reports_unit', 'reports', ['unit'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_file_hash'), 'uploaded_files', ['file_hash'], unique=True)
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_id'), 'actions', ['id'], unique=False)
    op.create_index(op.f('ix_actions_report_id'), 'actions', ['report_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_report_id'), 'reviews', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_report_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_actions_report_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_file_hash'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index('ix_reports_unit', table_name='reports')
    op.drop_index('ix_reports_site', table_name='reports')
    op.drop_index('ix_reports_sif_potential', table_name='reports')
    op.drop_index('ix_reports_risk_level', table_name='reports')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_date'), table_name='reports')
    op.drop_index('ix_reports_content_hash', table_name='reports')
    op.drop_index('ix_reports_category', table_name='reports')
    op.drop_index('ix_reports_barrier', table_name='reports')
    op.drop_index('ix_reports_area', table_name='reports')
    op.drop_index('ix_reports_activity', table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
